### ISSUE TITLE
How are Metadata Images being set?

### ISSUE THREAD

**Issue by btahir** [vercel-labs/ai-chatbot#72]
Hi - 

I've tried to replicate how you are rendering Twitter Card images but have been failing miserably. I see you have an opengraph-image.png and a twitter-image.png file at the root app level. This is not working for me. You also are generating this tag:

```<meta name="twitter:card" content="summary_large_image"/>```

The docs say the meta tag generated is summary and not summary_large_image. How are you doing this? Is there an extra step you have to do?

Also - unrelated but the favicon.ico file was supposed to be inside app folder according to the docs. But seems you made it work by having it in public?

Thanks!

**Comment by leerob** [comment]
> I see you have an opengraph-image.png and a twitter-image.png file at the root app level. This is not working for me.

What specifically isn't working? This file system metadata should generate the right tags for you based on the file.

> The docs say the meta tag generated is summary and not summary_large_image. How are you doing this? Is there an extra step you have to do?

We aren't modifying anything here related to that but you could set this value in `metadata` export for a given page, or the root layout.

> Also - unrelated but the favicon.ico file was supposed to be inside app folder according to the docs. But seems you made it work by having it in public?

The `favicon.ico` file can be placed in `app/` and things just work. The reason there's additional configuration here is because of the other alternate forms of icons for different devices provided in the `public/` folder. Those values are defined by `metadata` in the root layout.
